### ISSUE TITLE
can't use

### ISSUE THREAD

**Issue by Miku-chan39** [charlie-moomoo/3dviewer-short#1]
<img width="845" alt="截圖 2021-12-14 下午5 31 09" src="https://user-images.githubusercontent.com/72639017/146106262-ebe23a75-7d7f-4b11-8a29-e7efe4dd97e5.png">

url:https://3dv.c-moo.cf

**Comment by charlie-moomoo** [comment]
@cutebear0123 嗯正常
那個網域怪怪的

**Comment by Miku-chan39** [comment]
你的問題吧
https://pagespeed.web.dev/report?url=https%3A%2F%2F3dv.c-moo.cf%2F
顯示
 Lighthouse 傳回錯誤：NOT_HTML。提供的頁面未採用 HTML 格式 (以 MIME 類型 提供)。

**Comment by Miku-chan39** [comment]
https://dcr.c-moo.cf
就沒問題

**Comment by Miku-chan39** [comment]
建議用CNAME到https://github.com/charlie-moomoo/3dviewer

**Comment by charlie-moomoo** [comment]
我用cname啊
但就是不知為啥怪怪的 @cutebear0123

**Comment by charlie-moomoo** [comment]
>我用cname啊 但就是不知為啥怪怪的 @ cutebear0123

![Screenshot_2021-12-16-21-28-04-987](https://user-images.githubusercontent.com/65603222/146380965-691a633d-f223-448c-91d8-71c241513549.jpeg)

**Comment by Miku-chan39** [comment]
在github那邊也要設

**Comment by charlie-moomoo** [comment]
> 在github那邊也要設

@cutebear0123 
![image](https://user-images.githubusercontent.com/65603222/146660495-e6ee6614-1a1b-4da2-9d77-579a00b4e87e.png)
